### ISSUE TITLE
Make process_defines() easier to follow

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/otk#136]
Comment from @mvo5 in #129:

(nitpick) I was having a bit of a difficult time reading this, maybe just the sun. I wonder if a slightly diffrent way of phrasing it is easier to read (but maybe it's just me):
```python
diff --git a/src/otk/transform.py b/src/otk/transform.py
index fef9428..0e93cfc 100644
--- a/src/otk/transform.py
+++ b/src/otk/transform.py
@@ -148,14 +148,14 @@ def process_defines(ctx: Context, state: State, tree: Any):
             subblock.update(incl)
 
         if isinstance(value, dict):
-            # the value is a dict: process it recursively under a new subblock
-            new_subblock = {}
-            if isinstance(subblock.get(key), dict):
-                # If the new subblock already exists and is a dictionary, use it so they get merged
-                # Any other type will be replaced completely.
-                new_subblock = subblock[key]
-
-            # set the new subblock on the parent so that both context and subblock are available immediately
+            # The value is a dict: process recursively and keep track of
+            # new subblocks to keep track of nested values
+            new_subblock = subblock.get(key)
+            if not isinstance(new_subblock, dict):
+                # if the new block is not a dict it gets replaced completely,
+                # this happens e.g. when redefining vars
+                new_subblock = {}
+
             subblock[key] = new_subblock
             new_state = state.copy(defines=new_subblock)
             process_defines(ctx, new_state, value)
```
*but* I think something slightly deeper is irking me, it seems like the separation between "Context" and "State" is  a bit loose right now and Context._variables is refrenced from state but the connection is not super clear (to me)  - I have no good idea yet but I think this is part of my struggle :)

_Originally posted by @mvo5 in https://github.com/osbuild/otk/pull/129#discussion_r1651263922_
            
(see thread for further discussion)

---

Ideas for addressing this to make it easier to follow:
- Do not attach a reference to a subset of (or the whole) the global defines to the traversal State.  Instead, add a list of keys to the State that tracks which defines block is being processed.
```python
if isinstance(value, dict):
  ...
  new_state = state.copy(defines_key=key)
  process_includes(ctx, new_state, ...)
```

- Add new values to the global context directly, using the keys from the State.
```python
  ctx.defines[state.defines_key] = new_value  # update the context directly
```

- Clearly separate the three cases of interacting value types.
```python
if isinstance(value, dict) and isinstance(ctx.defines.get(key), dict):
  # merge code
elif isinstance(value, str):
  # do replacements on str
else:
  # the rest
```

- Do not expose the `ctx.defines` directly (revert b7b2aed7c18313c77e1e5e80e2aff2e2bfa7c90d).  Instead, use `ctx.variable`, which can handle nested keys (`ctx.variable("a.b")` -> `ctx.defines["a"]["b"]`).

**Comment by mvo5** [comment]
One short term idea I had is in https://github.com/osbuild/otk/pull/135 - but I think using the "defines_key" is the better medium/long term idea. It requires to make "Context.define()" aware of subkeys and merging of dicts so a bit more work than my (naive) renaming PR.

**Comment by achilleas-k** [comment]
> It requires to make "Context.define()" aware of subkeys and merging of dicts

I think making `Context.define()` symmetrical to `Context.variable()` in its handling of subkeys might be a nice feature.  It makes sense to me at least that the "getter" and "setter" would work with the same keys.
