### ISSUE TITLE
RFC: Default values for `otk.define` and default values of `${}`

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#17]
It is common for current users of `osbuild-mpp` to need defaults for variables; see for example the CentOS Automotive [default definitions](https://gitlab.com/CentOS/automotive/sample-images/-/blob/main/osbuild-manifests/include/defaults.ipp.yml) and [their selection](https://gitlab.com/CentOS/automotive/sample-images/-/blob/main/osbuild-manifests/include/computed-vars.ipp.yml).

This is used specifically in the definition part of the omnifest. Initially we had defined an `otk.argument` directive specifically for those things that are passed from outside: https://github.com/osbuild/otk/pull/7 which might cover some of the usecases here.

We currently *forbid* redefining an `otk.define`'d name with a new value, I propose we keep doing so as it leads to weird state on when things are available but get overwritten by things deeper in the tree.

I propose the following syntax for default variable values:

```yaml
otk.default:
  name: "foo"
  list:
    - 1
    - 2

otk.define:
  name: "bar"
```

Would lead to any lookup of `${name}` to be resolved to `"bar"` and a lookup of `${list}` to be resolved to the default value of `[1,2]`.

The other issue is usage, sometimes you want to take some action based on a value not existing. I propose this option:

Reintroduce `otk.variable` syntax. This is consistent with other directives that take arguments. The default is only used if `list` is *not* defined. Not when it is defined to something Falseyish.

```yaml
otk.variable:
  name: list
  default:
    - 1
    - 2
```
Alternatively we *could* explore a system where an undefined variable is not an error but instead becomes falseyish, in that case it could work together with a future `otk.op.if` or `otk.op.or`.

**Comment by mvo5** [comment]
Is there a concrete (ideally small) real world example how this is used by automotive? Any link or file or pasted example would be most welcome :)

**Comment by supakeen** [comment]
Not quite small but there are links to use by automotive in the OP.

**Comment by supakeen** [comment]
Right, that could live in the linter or logs.

And I assume that defines from the command line always win

**Comment by supakeen** [comment]
No longer necessary after a long chat yesterday and the approval of #18.
