### ISSUE TITLE
Please add a `otk.meta` example

### ISSUE THREAD

**Issue by mvo5** [osbuild/otk#2]
I'm struggling a bit to understand the `otk.meta` directive. Right now it says:
```
Under the `otk.meta` namespace any data can be stored that other applications
need to use from an omnifest.

Expects a `map` for its value.

otk.meta.osbuild-composer:
  boot_mode: uefi
```
I would love an example what is done with the data, is it put into the generated manifest.json? is it just part of the .otk file for other tools to inspect?

Related to this to me it is not clear why it's it's own directive. I wonder if we could define the metadata just via the normal `otk.define`.
So
```yaml
otk.define:
 meta:
  osbuild-composer:
   export: image
```
i.e. I think I would love to have some example/explaination how this will be used.

**Comment by supakeen** [comment]
This is going to be superceded by #85.
