### ISSUE TITLE
Switch to an event-based YAML parser

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#47]
This is a big issue. Currently we use `pyyaml` directly by loading a string. This makes us lose information about where certain things live in the document.

If we were to switch to an event-based parser we could build an alternative tree that contains both the data and the metadata about where a certain node was first encountered. This would lead to much better error reporting.

**Comment by ondrejbudai** [comment]
An alternative approach is to define a json schema for omnifests. Would be quite cool because we can do basic validation and some editors can take advantage of this when offering autocomplete.

**Comment by supakeen** [comment]
Schemata for inputs (and perhaps outputs) are definitely something that should go on the list.

This issue just got a bit more important due to #62 and if we decide to *not* support other formats (#48) then I think the above is going to be necessary.
