### ISSUE TITLE
Do we want to support multiple omnifest formats?

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#48]
Currently omnifests are expected to be YAML. Internally we only deal with tree structures which can also be represented in TOML, and JSON.

Do we want to accept those formats for omnifests?

Note that this could clash with #47.

**Comment by ondrejbudai** [comment]
I don't see a reason to accept more formats. Additionally, yaml is basically a superset of json, so we actually have jsn covered.

**Comment by bcl** [comment]
Originally I thought it would be nice to also support TOML, but then I converted some example into TOML and, well, as much as it pains me to say it, even for humans I think the YAML version is far easier to read and edit.

**Comment by supakeen** [comment]
> Originally I thought it would be nice to also support TOML, but then I converted some example into TOML and, well, as much as it pains me to say it, even for humans I think the YAML version is far easier to read and edit.

This has also been my experience. When things get nested deeply and especially when sequences and maps are mixed together at those deeper levels things start getting very funky in TOML.

**Comment by supakeen** [comment]
We will go with only YAML support initially.
